name = "BroadcastMapConversion"
uuid = "4a4adec5-520f-4750-bb37-d5e66b4ddeb2"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.3"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"

[compat]
BlockArrays = "1.3.0"
FillArrays = "1.13.0"
julia = "1.10"
