name = "BroadcastMapConversion"
uuid = "7726166c-068e-4473-bed7-0e8eb0255830"
authors = ["ITensor developers"]
version = "0.1.0"

[compat]
Aqua = "0.8.9"
SafeTestsets = "0.1"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "SafeTestsets"]
